[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "nyc-fhvhv-analysis"
version = "0.1.0"
description = "NYC FHVHV demand analysis and forecasting"
dependencies = [
    "duckdb",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "pmdarima",
    "scikit-learn",
    "requests",
]

[tool.setuptools.packages.find]
where = ["src"]